name: vanillamlp
model: mlp
num_seeds: 10
selection: rand
is_shared: true
batch_norm: false
epoch: 1000
batch_size: 500
learning_rate: 0.00005
rep_dim: 4
hidden_dim: 128
enc_depth_shared: 4
enc_depth_task: 2
dec_depth_shared: 2
dec_depth_task: 1
in_size: 24
device: cuda
load: null
save: results/training
task_sequence: null